# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'dragged-bottom-card-Test' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for dragged-bottom-card-Test
  pod 'SnapKit', '~> 5.0.0'
  pod 'Charts'
end
