# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'swimming-test-app-2' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for swimming-test-app-2
  pod 'CSV.swift', '~> 2.4.3'
end
